# ╭─────────────────────────          ImplementationGuide Notes         ───────────────────────────╮
# | This is an initial configuration file for a template IG for Australian context.                |
# | Please modify the information below to match the requirements of your own IG.                  |
# | The canonical URL will need to be changed once a suitable URL is agreed upon and available.    |
# | The menu structure will be customized as required to fit the content of the IG.                |
# | The version should be updated for each release of the IG, in accord with versioning policy.    |
# | Keep the fhirVersion and instanceOptions settings unless specific reasons to change them.      |
# ╰───────────────────────────────────────────────────────────────────────────────────────────────╯
id: hello.fhir.ig.au
packageId: hello.fhir.ig.au
canonical: https://healthinfoservices.net/hello-fhir-ig-au
name: HelloAuFHIRIG
title: Template FHIR Implementation Guide in Australian Context
description: This Implementation Guide template has been developed to assist Australian implementers to get started with IG Authoring.
status: draft # draft | active | retired | unknown
version: 0.1.0
copyrightYear: 2026+
releaseLabel: ci-build
license: MIT
copyright: Daniel Foulkes (HealthInfoServices)

# publisher information
publisher:
  name: HealthInfoServices
  url: https://healthinfoservices.net

menu:
  Home: index.html
  Getting Started: gettingstarted.html
  Data Types: datatypes.html
  Resources: resources.html
  Terminology: terminology.html
  Extensions: extensions.html
  Artifacts: artifacts.html

# contact
contact:
  - name: Support
    telecom:
      - system: url
        value: https://www.healthinfoservices.net


pages:
  index.md:
    title: Template Implementation Guide
  gettingstarted.md:
    title: Authoring a FHIR IG using this template
  datatypes.md:
    title: Data Type Profiles
  resources.md:
    title: Resource Profiles
  terminology.md:
    title: Terminology
  extensions.md:
    title: Extensions

fhirVersion: 4.0.1
dependencies:
  hl7.fhir.au.core: 2.0.0
  hl7.fhir.au.base: 6.0.0
jurisdiction: urn:iso:std:iso:3166#AUS "Australia"
instanceOptions:
  manualSliceOrdering: true